const products = [
  {
    id: 2,
    name: "Tomatoes",
    description:
      "Experience the rich, robust flavor of our sun-ripened tomatoes. Perfect for salads, sauces, and slicing, our tomatoes are hand-picked for their vibrant color and firmness.",
    category: "Veggies",
    price: 1200,
    image: "/assets/tomatoes.png",
    pricePer: "per Kilogram",
    rating: 410,
    stars: 4,
  },
  {
    id: 3,
    name: "Onions",
    description:
      "Add depth and intensity to any dish with our premium onions. Grown in fertile soil, these onions provide a strong, yet sweet flavor when cooked.",
    category: "Veggies",
    price: 900,
    image: "/assets/onions.png",
    pricePer: "per Kilogram",
    rating: 325,
    stars: 4,
  },
  {
    id: 4,
    name: "Lemon",
    description:
      "Our zesty lemons are bursting with tangy flavor and a vibrant, juicy freshness that enhances beverages, marinades, and dressings.",
    category: "Fruits",
    price: 400,
    image: "/assets/lemon.png",
    pricePer: "per Whole",
    rating: 270,
    stars: 4,
  },
  {
    id: 5,
    name: "Scotch Bonnets",
    description:
      "Turn up the heat with our fiery Scotch Bonnet peppers. Ideal for those who dare to explore spicy cuisines, these peppers are a staple in Caribbean dishes.",
    category: "Veggies",
    price: 600,
    image: "/assets/scotch.png",
    pricePer: "per Kilogram",
    rating: 200,
    stars: 5,
  },

  {
    id: 6,
    name: "Eggplant",
    description:
      "Our eggplants boast a glossy exterior and a spongy texture that absorbs flavors beautifully, making them perfect for your culinary experiments.",
    category: "Veggies",
    price: 900,
    image: "/assets/Egg-plant.png",
    pricePer: "per Whole",
    rating: 150,
    stars: 3,
  },
  {
    id: 7,
    name: "Bananas",
    description:
      "Enjoy the smooth, creamy texture and natural sweetness of our bananas. Grown in tropical climates, they are an excellent source of energy and potassium.",
    category: "Fruits",
    price: 1000,
    image: "/assets/Banana.png",
    pricePer: "per Bunch",
    rating: 480,
    stars: 4,
  },
  {
    id: 8,
    name: "Pineapple",
    description:
      "Our pineapples are picked at peak ripeness, ensuring each bite is infused with an intense sweetness that's second to none.",
    category: "Fruits",
    price: 1900,
    image: "/assets/Pineapple.png",
    pricePer: "per Whole",
    rating: 390,
    stars: 4,
  },
  {
    id: 1,
    name: "Lettuce Leaf",
    description:
      "Discover the unparalleled freshness and quality of our farm-fresh lettuce, harvested daily from our local fields. Our lettuce is nurtured with care, ensuring that each leaf is packed with flavor and nutrients.",
    category: "Veggies",
    price: 900,
    image: "/assets/lettuce.png",
    pricePer: "per Bundle",
    rating: 530,
    stars: 5,
  },
  {
    id: 9,
    name: "Cucumbers",
    description:
      "Crisp and refreshing, our cucumbers are perfect for salads or as a cool snack on a hot day.",
    category: "Veggies",
    price: 700,
    image: "/assets/cucumbers.png",
    pricePer: "per Kilogram",
    rating: 320,
    stars: 3,
  },
  {
    id: 10,
    name: "Carrots",
    description:
      "Our carrots are sweet and crunchy, ideal for snacking, stews, or side dishes.",
    category: "Veggies",
    price: 800,
    image: "/assets/carrots.png",
    pricePer: "per Kilogram",
    rating: 410,
    stars: 4,
  },
  {
    id: 11,
    name: "Spinach",
    description:
      "Rich in nutrients and flavor, our spinach is tender and ideal for salads or cooking.",
    category: "Veggies",
    price: 500,
    image: "/assets/spinach.png",
    pricePer: "per Bundle",
    rating: 365,
    stars: 4,
  },
  {
    id: 12,
    name: "Mangoes",
    description:
      "Juicy and sweet, our mangoes are a tropical delight, perfect for desserts or smoothies.",
    category: "Fruits",
    price: 1500,
    image: "/assets/mango.png",
    pricePer: "per Kilogram",
    rating: 450,
    stars: 5,
  },
  {
    id: 13,
    name: "Apples",
    description:
      "Crisp and juicy, our apples are a healthy snack packed with flavor.",
    category: "Fruits",
    price: 1200,
    image: "/assets/apple.png",
    pricePer: "per Kilogram",
    rating: 490,
    stars: 4,
  },
  {
    id: 14,
    name: "Oranges",
    description:
      "Bursting with vitamin C, our oranges are sweet and perfect for juicing or peeling.",
    category: "Fruits",
    price: 800,
    image: "/assets/orange.png",
    pricePer: "per Kilogram",
    rating: 430,
    stars: 4,
  },
  {
    id: 15,
    name: "Sweet Potatoes",
    description:
      "Nutritious and filling, our sweet potatoes are versatile for meals at any time of the day.",
    category: "Veggies",
    price: 1100,
    image: "/assets/sweetpotato.png",
    pricePer: "per Kilogram",
    rating: 340,
    stars: 4,
  },
  {
    id: 16,
    name: "Avocados",
    description:
      "Rich and creamy, our avocados add a smooth texture and healthy fats to any dish.",
    category: "Fruits",
    price: 1800,
    image: "/assets/avocado.png",
    pricePer: "per Kilogram",
    rating: 480,
    stars: 5,
  },
  {
    id: 17,
    name: "Pears",
    description:
      "Sweet and soft, our pears are delightfully juicy and ideal for a quick snack or dessert.",
    category: "Fruits",
    price: 1300,
    image: "/assets/pear.png",
    pricePer: "per Kilogram",
    rating: 410,
    stars: 4,
  },
  {
    id: 18,
    name: "Watermelon",
    description:
      "Juicy and hydrating, our watermelons are a summer favorite for refreshment and sweetness.",
    category: "Fruits",
    price: 900,
    image: "/assets/watermelon.png",
    pricePer: "per Whole",
    rating: 400,
    stars: 4,
  },
  {
    id: 19,
    name: "Cherries",
    description:
      "Our cherries are sweet and tart, perfect for baking or as a delightful snack.",
    category: "Fruits",
    price: 2200,
    image: "/assets/cherries.png",
    pricePer: "per Kilogram",
    rating: 390,
    stars: 4,
  },
  {
    id: 20,
    name: "Broccoli",
    description:
      "Rich in nutrients and great for steaming or stir-frying, our broccoli is fresh and green.",
    category: "Veggies",
    price: 900,
    image: "/assets/broccoli.png",
    pricePer: "per Kilogram",
    rating: 350,
    stars: 4,
  },
  {
    id: 21,
    name: "Mushrooms",
    description:
      "Earthy and rich, our mushrooms are great for soups, salads, or sautéing.",
    category: "Veggies",
    price: 1200,
    image: "/assets/mushrooms.png",
    pricePer: "per Kilogram",
    rating: 415,
    stars: 5,
  },
  {
    id: 22,
    name: "Peas",
    description:
      "Sweet and tiny, our peas are perfect for adding to dishes or as a side.",
    category: "Veggies",
    price: 500,
    image: "/assets/peas.png",
    pricePer: "per Kilogram",
    rating: 280,
    stars: 3,
  },
  {
    id: 23,
    name: "Cauliflower",
    description:
      "Our cauliflower is versatile and nutritious, ideal for roasting or as part of your favorite dishes.",
    category: "Veggies",
    price: 950,
    image: "/assets/cauliflower.png",
    pricePer: "per Whole",
    rating: 330,
    stars: 4,
  },
  {
    id: 24,
    name: "Garlic",
    description:
      "Bold and aromatic, our garlic will enhance any meal with its powerful flavor.",
    category: "Veggies",
    price: 600,
    image: "/assets/garlic.png",
    pricePer: "per Kilogram",
    rating: 460,
    stars: 5,
  },
  {
    id: 25,
    name: "Red Peppers",
    description:
      "Sweet and vibrant, our red peppers are perfect for salads, grilling, or stuffing.",
    category: "Veggies",
    price: 1300,
    image: "/assets/redpeppers.png",
    pricePer: "per Kilogram",
    rating: 420,
    stars: 4,
  },
  {
    id: 26,
    name: "Zucchini",
    description:
      "Our zucchini is tender and versatile, ideal for grilling, baking, or making zoodles.",
    category: "Veggies",
    price: 700,
    image: "/assets/zucchini.png",
    pricePer: "per Kilogram",
    rating: 300,
    stars: 3,
  },
  {
    id: 27,
    name: "Grapes",
    description:
      "Sweet and juicy, our grapes are perfect for snacking or making wine.",
    category: "Fruits",
    price: 2100,
    image: "/assets/grapes.png",
    pricePer: "per Kilogram",
    rating: 470,
    stars: 4,
  },
  {
    id: 28,
    name: "Kiwi",
    description:
      "Tangy and sweet, our kiwi is a nutritional powerhouse, great for salads or as a snack.",
    category: "Fruits",
    price: 2500,
    image: "/assets/kiwi.png",
    pricePer: "per Kilogram",
    rating: 460,
    stars: 5,
  },
  {
    id: 29,
    name: "Papaya",
    description:
      "Our papaya is soft and sweet, with a tropical flavor that enhances any fruit salad.",
    category: "Fruits",
    price: 1900,
    image: "/assets/papaya.png",
    pricePer: "per Whole",
    rating: 380,
    stars: 4,
  },
  {
    id: 30,
    name: "Blueberries",
    description:
      "Our blueberries are plump and sweet, perfect for baking or topping your morning cereal.",
    category: "Fruits",
    price: 3000,
    image: "/assets/blueberries.png",
    pricePer: "per Kilogram",
    rating: 490,
    stars: 5,
  },
  {
    id: 31,
    name: "Asparagus",
    description:
      "Tender and flavorful, our asparagus is ideal for grilling or as a classy side dish.",
    category: "Veggies",
    price: 2200,
    image: "/assets/asparagus.png",
    pricePer: "per Bundle",
    rating: 410,
    stars: 4,
  },
  {
    id: 32,
    name: "Celery",
    description:
      "Crisp and refreshing, our celery is perfect for juicing or snacking.",
    category: "Veggies",
    price: 800,
    image: "/assets/celery.png",
    pricePer: "per Bundle",
    rating: 300,
    stars: 3,
  },
];

export default products;
